export const puppeteerArgs = [
  "--no-sandbox",
  "--disable-gpu-driver-bug-workarounds",
  "--disable-setuid-sandbox",
  "--unhandled-rejections=strict",
  "--disable-dev-shm-usage",
  "--disable-accelerated-2d-canvas",
  "--no-first-run",
  "--no-zygote",
  "--disable-gpu",
  "--log-level=3",
  "--no-default-browser-check",
  "--disable-site-isolation-trials",
  "--no-experiments",
  "--ignore-gpu-blacklist",
  "--ignore-certificate-errors",
  "--ignore-certificate-errors-spki-list",
  "--disable-extensions",
  "--disable-default-apps",
  "--enable-features=NetworkService",
  "--disable-webgl",
  "--disable-threaded-animation",
  "--disable-threaded-scrolling",
  "--disable-in-process-stack-traces",
  "--disable-histogram-customizer",
  "--disable-gl-extensions",
  "--disable-composited-antialiasing",
  "--disable-canvas-aa",
  "--disable-3d-apis",
  "--disable-accelerated-jpeg-decoding",
  "--disable-accelerated-mjpeg-decode",
  "--disable-app-list-dismiss-on-blur",
  "--disable-accelerated-video-decode",
];

export const puppeteerConfig = {
  headless: true,
  ignoreDefaultArgs: ["--enable-automation", "--disable-dev-shm-usage"],
  args: puppeteerArgs,
  pipe: true,
};
